library(tidyverse)
library(jsonlite)
library(curl)
library(pdftools)
library(tm)
library(tidytext)
library(textdata)
library(scales)
library(ggtext)
library(vars)
library(lmtest)
library(wordcloud2)

source('01_get_atas.R')
source('02_get_transform_atas.R')
source('03_get_Loughran_McDonald.R')
source('04_get_sentiment_analysis.R')
source('05_get_wordclouds.R')
source('06_get_series.R')
source('07_get_transform_dataset.R')
source('08_get_graphics.R')
source('09_get_OLS_models.R')

atas = get_atas()
atas_token = get_transform_atas(atas)
Loughran_McDonald = get_Loughran_McDonald()
sentiment_analysis = get_sentiment_analysis(atas_token, Loughran_McDonald)
wordclouds = get_wordclouds(atas_token)
timeseries = get_series()
dataset_fit = get_transform_dataset(timeseries, sentiment_analysis)
grafico_ts = get_graphics(sentiment_analysis, dataset_fit)
modelo = get_model(dataset_fit)
modelo_diff = get_model_diff(dataset_fit)